import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const nunito_Sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mortgage Calculator",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${nunito_Sans.className} bg-[#F7F8FA]`}>
        {children}
      </body>
    </html>
  );
}
